version: '3.8'

services:
  axon-server:
    image: axoniq/axonserver:latest-jdk-17-dev
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_autocluster_first: axon-server
      axoniq_axonserver_autocluster_contexts: _admin,default
    volumes:
      - data:/axonserver/data
      - events:/axonserver/events

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_PORT: "27017"

volumes:
  data:
    driver: local
  events:
    driver: local
  mongo_data:
    driver: local
